spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/popcornmeter
    username: pm_user
    password: pm_pwd

  security:
    user:
      name: admin
      password: admin

  jpa:
    show-sql: true

logging:
  level:
    uk.sky.pm: DEBUG

management:
  endpoints:
    web.exposure.include: "*"
  prometheus.metrics.export.enabled: true